ALTER TABLE dim_state ADD COLUMN state_abbr TEXT;

UPDATE dim_state SET state_abbr = CASE state_code
    WHEN 1 THEN 'AL' WHEN 2 THEN 'AK' WHEN 4 THEN 'AZ' WHEN 5 THEN 'AR'
    WHEN 6 THEN 'CA' WHEN 8 THEN 'CO' WHEN 9 THEN 'CT' WHEN 10 THEN 'DE'
    WHEN 11 THEN 'DC' WHEN 12 THEN 'FL' WHEN 13 THEN 'GA' WHEN 15 THEN 'HI'
    WHEN 16 THEN 'ID' WHEN 17 THEN 'IL' WHEN 18 THEN 'IN' WHEN 19 THEN 'IA'
    WHEN 20 THEN 'KS' WHEN 21 THEN 'KY' WHEN 22 THEN 'LA' WHEN 23 THEN 'ME'
    WHEN 24 THEN 'MD' WHEN 25 THEN 'MA' WHEN 26 THEN 'MI' WHEN 27 THEN 'MN'
    WHEN 28 THEN 'MS' WHEN 29 THEN 'MO' WHEN 30 THEN 'MT' WHEN 31 THEN 'NE'
    WHEN 32 THEN 'NV' WHEN 33 THEN 'NH' WHEN 34 THEN 'NJ' WHEN 35 THEN 'NM'
    WHEN 36 THEN 'NY' WHEN 37 THEN 'NC' WHEN 38 THEN 'ND' WHEN 39 THEN 'OH'
    WHEN 40 THEN 'OK' WHEN 41 THEN 'OR' WHEN 42 THEN 'PA' WHEN 44 THEN 'RI'
    WHEN 45 THEN 'SC' WHEN 46 THEN 'SD' WHEN 47 THEN 'TN' WHEN 48 THEN 'TX'
    WHEN 49 THEN 'UT' WHEN 50 THEN 'VT' WHEN 51 THEN 'VA' WHEN 53 THEN 'WA'
    WHEN 54 THEN 'WV' WHEN 55 THEN 'WI' WHEN 56 THEN 'WY'
END;